### ISSUE TITLE
Testing 1.9.2 and WordPress 4.5.2

### ISSUE THREAD

**Issue by zuricx1** [woocommerce/sensei-media-attachments#11]
Hey im using 1.9.2 and WP 4.5.2, things are not going so well. The Sensei media attachment doesn't appear when I go ahead and create a new lesson or course. Any ideas?

**Comment by donnapep** [comment]
@zuricx1 Was this ever resolved, or is it still an issue? Thx!

**Comment by donnapep** [comment]
Closing as stale.
