### ISSUE TITLE
Replace deprecated hooks

### ISSUE THREAD

**Issue by luisrock** [woocommerce/sensei-media-attachments#13]
This plugin make use of hooks that are deprecated from Sensei 1.9 on.

Hooks are: `sensei_lesson_single_meta` and `sensei_course_single_lessons`.

Is this plugin abandoned? Never had an update...strange.

**Comment by lvnilesh** [comment]
Appreciate your help with a code cleanup.

https://github.com/woocommerce/sensei-content-drip/issues/119

**Comment by aheckler** [comment]
522589-zd-woothemes

**Comment by donnapep** [comment]
Both `sensei_course_single_lessons` and `sensei_lesson_single_meta` are deprecated. Should be using `sensei_single_course_content_inside_after` and `sensei_single_lesson_content_inside_after`, respectively.

**Comment by donnapep** [comment]
Fixed by #20.
