### ISSUE TITLE
Use media title as name of media attachment

### ISSUE THREAD

**Issue by jenhooks** [woocommerce/sensei-media-attachments#14]
Currently, media attachments display in the lesson using the file name, and they're ugly:

<img width="1001" alt="ugly_media_attachments" src="https://cloud.githubusercontent.com/assets/7585054/18926927/a0cc41b6-8587-11e6-918b-ed4635f71f1f.png">

Can we have those names obey the title assigned to the media file when it is uploaded? Or add a field allowing the user to assign a more tidy name to the upload, within the Lesson Media module itself?

Reference: 473898-zd-woothemes

**Comment by donnapep** [comment]
See [here](https://pippinsplugins.com/retrieve-attachment-id-from-image-url/) for getting the attachment ID from the URL.

Where a media file does not have a title, the name should fallback to the URL by default.

**Comment by donnapep** [comment]
@jenhooks Would appreciate a quick test of this change as you are the OP. 🙂
