### ISSUE TITLE
Upgrade to latest version removed all attachments from all lessons

### ISSUE THREAD

**Issue by beags121** [woocommerce/sensei-media-attachments#21]
I'm not entirely sure when/how this happened but a some point between updating to the latest version of Woocommerce and now - all attachments were removed from all lessons. Only a customer managed to discover this.

**Comment by donnapep** [comment]
@beags121 Can you please provide a bit more information? What version of WooCommerce were you upgrading from and to? Have you since found the attachments, or are they still missing? Thx.

**Comment by donnapep** [comment]
Closing as stale.
