### ISSUE TITLE
Reference to an obsolete hook

### ISSUE THREAD

**Issue by gaurav1984** [woocommerce/sensei-media-attachments#23]
The user in 866903-zen is reporting that the Sensei Media attachments plugin references an obsolete hook in **/classes/class-sensei-media-attachments.php** on _Line No. 31_

They are proposing that the following code should fix the issue.

`add_action( 'sensei_single_course_content_inside_after', array( $this, 'display_attached_media' ), 9 );`

Please have a look!
Thanks :)

**Comment by donnapep** [comment]
Both `sensei_course_single_lessons` and `sensei_lesson_single_meta` are deprecated. Should be using `sensei_single_course_content_inside_after` and `sensei_single_lesson_content_inside_after`, respectively.

**Comment by donnapep** [comment]
Duplicate of #13.
