### ISSUE TITLE
Course Media should not be visible in some scenarios

### ISSUE THREAD

**Issue by donnapep** [woocommerce/sensei-media-attachments#25]
Course Media should **NOT** be visible in the following scenarios:

_Free Course_
- _Users must be logged in to view Course and Lesson content_ setting is checked but the user is not logged in.
- _Users must be logged in to view Course and Lesson content_ setting is checked, the user is logged in but they are not enrolled in the course.

_Paid Course_
- User is not logged in
- User is logged in but has not purchased the course

Note that the _Users must be logged in to view Course and Lesson content_ setting is not applicable for paid courses.

**Comment by bryan-farris** [comment]
Any update on this?

**Comment by donnapep** [comment]
Sorry, but we don't have an update at this time.

**Comment by donnapep** [comment]
Closing as this has been addressed by https://github.com/woocommerce/sensei-media-attachments/issues/41. We can iterate again should we receive additional feedback.
