### ISSUE TITLE
Change the two-column media attachment layout to a single column layout

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/sensei-media-attachments#27]
Reported on 1368032-zen 

The  current layout of the media attachments is by default in two columns, which makes it not consistent with the rest of the design, and the boxes could make the information hard to read. Would be great to switch this to a single line per attachment.

This can be seen under Lessons > Add New > Lesson Media

<img width="919" alt="screen shot 2018-09-04 at 13 12 16" src="https://user-images.githubusercontent.com/3812076/45013132-31871080-b044-11e8-9417-d3ec4da47080.png">

The user also provided their own custom code that works on their site:

```
function isa_admin_styles() {
echo '<style>
#sensei_media_attachments td {
display: flex;
}
#sensei_media_attachments td input[type="text"] {
flex-grow: 10;
}
</style>';
}

add_action('admin_head', 'isa_admin_styles'); 



```

**Comment by donnapep** [comment]
@iamgabrielma Would appreciate a quick test of this change as you are the OP. 🙂
