### ISSUE TITLE
Course and Lesson Media should not be visible to users who are not taking a course

### ISSUE THREAD

**Issue by donnapep** [woocommerce/sensei-media-attachments#41]
#### Steps to Reproduce
1. Add course media to a course and lesson media to a lesson.
2. On the front-end, browse to the course and lesson as an anonymous visitor or as a logged in user who is not taking the course.
3. Note that both the course and lesson media are visible.

#### What I Expected
Course and lesson media should not be visible.

#### What Happened Instead
Course and lesson media are visible to site visitors who are not taking the associated course.

#### PHP / WordPress / Sensei version
7.2.9 / 5.1 / 1.12.2

We should also add hooks for both course and lesson media so that if a site owner _does_ want to display either or both, they can do so.

**Comment by richardmtl** [comment]
Reported in 1873205-zen (noting here so I can get back to her about it when fixed).

**Comment by richardmtl** [comment]
Another: 1882323-zen

**Comment by codestor4** [comment]
The user says this doesn't fix the issue for "course videos". Here's a quote from the ticket - 

> The update is working well for hiding attachments from non-purchasers  :-)
But this update doesn't include hiding Course Videos.
Can you send me updated PHP code that allows me to hide Course Videos?

They also shared the code that Donna shared with them before, which is - 

```
add_action( 'wp_head', 'reattach_hook' );

function reattach_hook() { 
global $sensei_media_attachments;

remove_action( 'sensei_single_course_content_inside_before', array( 'Sensei_Course', 'the_course_video' ), 40 ); 
remove_action( 'sensei_single_course_content_inside_after', array( 'Sensei_Course', 'the_course_lessons_title' ), 9 ); 
remove_action( 'sensei_single_course_content_inside_after', 'course_single_lessons', 10 ); 
remove_action( 'sensei_single_course_content_inside_before', array( $sensei_media_attachments, 'display_attached_media' ), 35 ); 
add_action( 'sensei_single_course_content_inside_before', 'maybe_show_attached_media', 35 ); 
}

function maybe_show_attached_media() { 
$is_user_taking_course = Sensei_Utils::user_started_course( get_the_ID(), get_current_user_id() );

if ( $is_user_taking_course ) { 
global $post;

Sensei_Course::the_course_video(); 
Sensei_Course::the_course_lessons_title(); 
course_single_lessons();

$media = get_post_meta( $post->ID, '_attached_media', true );

if( ! is_array( $media ) || 0 === count( $media ) ) { 
return; 
}

$post_type = get_post_type( $post );

if ( ! in_array( $post_type, array( 'course', 'lesson' ), true ) ) { 
return; 
}

$media_heading = ( 'lesson' === $post_type ) ? 
__( 'Lesson Media', 'sensei_media_attachments' ) : 
__( 'Course Media', 'sensei_media_attachments' );

$html = ''; 
$html .= '' . esc_html( $media_heading ) . ''; 
$html .= '';

foreach( $media as $k => $file ) { 
$file_parts = explode( '/', $file ); 
$file_name = array_pop( $file_parts ); 
$html .= '' . esc_html( $file_name ) . ''; 
}

$html .= '';

echo $html; 
} 
}
```

cc: @donnapep @alexsanford Can you have a look and advice on what can we do next?

**Comment by donnapep** [comment]
@codestor4 This isn't meant to do anything for course videos as that is part of Sensei and not Media Attachments.
