### ISSUE TITLE
Attached media files don't appear on lesson pages for admins

### ISSUE THREAD

**Issue by amroland** [woocommerce/sensei-media-attachments#57]
Attached media files don't appear on Lesson pages.

#### Steps to Reproduce
1. Add some media file on the Lesson Media panel of any Lesson page.
2. Publish.
3. Look at it on the front page.

#### What I Expected
Media files should listed under the content of the lesson.

#### What Happened Instead
No media file listing appears.

#### PHP / WordPress / Sensei version
WordPress 5.1.1.
Sensei 1.12.3, Sensei 2.0.0. and Sensei LMS 2.0.1.
Sensei Media Attachments 1.0.2 and 2.0.0

**Comment by danjjohnson** [comment]
Same issue reported in 2328965-zen:

- Logged into staging site
- Switched to 2019 theme (also tried with 2017 to be sure).
- Deactivated all plugins except SWCPC, Media Attachments, and WooCommerce.
- Viewed lesson
- Lesson Media is not shown

Further details and login credentials in the ticket.

**Comment by danjjohnson** [comment]
Ok, thanks to 2394283-zen we have confirmed that you have to be assigned to the course to see the lesson media, even if you're an admin user.

I'm not sure if this has always been the case, but perhaps we should allow admins to always see the lesson media even if they are not taking the course.
